config/routes.rb
Hackline::Application.routes.draw do
  
  resources :project_assignments

  resources :timelines

  
  resources :tasklists do
    resources :tasks do
      member do
        put 'start'
        put 'unstart'
        put 'done'
        put 'undone'
        put 'favorite'
        put 'unfavorite'
      end
    end
  end

  resources :projects do
    member do
      put 'active'
      put 'inactive'
      put 'done'
      put 'undone'
      get 'manage_team'
      post 'manage_team'
    end
    
    resources :tasklists
  end

  devise_for :users

  root :to => "projects#index"

end

app/models/favorite_task.rb
class FavoriteTask < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasklists, :dependent => :destroy
  has_many :project_assignments, :dependent => :destroy
  def to_s
    return self.name
  end
  
  def team
    result = []
    project_assignments.each do |assignment|
      result.push assignment.user
    end
    return result
  end
end

app/models/project_assignment.rb
class ProjectAssignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :tasklist
  belongs_to :user
  
  has_many :task_assignments, :dependent => :destroy
  has_many :assigned_users, :through => :task_assignments, :source => :user
  
  def to_s
    return self.body
  end
  
  #Favorite Task
  has_many :favorite_tasks
  has_many :favorited_by_users, :through => :favorite_tasks, :source => :user
end

app/models/task_assignment.rb
class TaskAssignment < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

app/models/tasklist.rb
class Tasklist < ActiveRecord::Base
  belongs_to :project
  has_many :tasks, :dependent => :destroy

  def assigned_users
    people = []
    self.tasks.each do |task|
      people += task.assigned_users
    end
    return people.uniq
  end

  def to_s
    return self.name
  end
end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :favorite_tasks
  has_many :favorited_tasks, :through => :favorite_tasks, :source => :task
  
  
  has_many :project_assignments, :dependent => :destroy
  
  
  def to_s
    return self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/favorite_tasks_controller.rb
class FavoriteTasksController < InheritedResources::Base
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  before_filter :authenticate_user!
  respond_to :html, :js
  
  def active
    resource.active = true
    resource.save
    redirect_to collection_url, :notice => "Task: #{resource.body} is done!"
  end
  
  def inactive
    resource.active = false
    resource.save
    redirect_to collection_url, :notice => "Task: #{resource.body} is undone!"
  end
  
  def done
    resource.done = true
    resource.completed_on = DateTime.now
    resource.save
    redirect_to collection_url, :notice => "Task: #{resource.body} is done!"
  end
  
  def undone
    resource.done = false
    resource.completed_on = nil
    resource.save
    redirect_to collection_url, :notice => "Task: #{resource.body} is undone!"
  end
  
  def manage_team
    @team = resource.team
    @remaining_users = User.all - @team
    
    team = []
    if params[:method] == "post"
      if params[:team] != nil
        params[:team].each do |key, value|
          user_id = key.gsub("user_", "").to_i
          team.push User.find(user_id)
        end
      end
      
      
      
      add_users = team - @team
      remove_users = @team - team
    
      remove_users.each do |user|
        project_assignment = ProjectAssignment.where("user_id = '#{user.id}' AND project_id = '#{resource.id}'")
        logger.error project_assignment[0].inspect
        project_assignment[0].destroy
      end
    
      add_users.each do |user|
        ProjectAssignment.create(:user_id=> user.id, :project_id => resource.id)
      end
      
    end
    
    @team = team if team
    @remaining_users = User.all - @team
      
  end
  
  
  
end

app/controllers/task_assignments_controller.rb
class TaskAssignmentsController < InheritedResources::Base
end

app/controllers/tasklists_controller.rb
class TasklistsController < InheritedResources::Base
  belongs_to :project, :optional => true

  before_filter :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < InheritedResources::Base
  belongs_to :tasklist, :optional => true
  
  before_filter :authenticate_user!
  
  def create
    @task = Task.new(params[:task])
    
    #Assign the current user as the creator of that task
    @task.user = current_user
    
    create!
  end
  
  def start
    resource.started = DateTime.now
    resource.save
    redirect_to collection_url, :notice => "Task: #{resource.body} has been started!"
  end
  
  def unstart
    resource.started = nil
    resource.save
    redirect_to collection_url, :notice => "Task: #{resource.body} has been unstarted!"
  end
  
  def done
    resource.done = true
    resource.completed_on = DateTime.now
    resource.save
    redirect_to collection_url, :notice => "Task: #{resource.body} is done!"
  end
  
  def undone
    resource.done = false
    resource.completed_on = nil
    resource.save
    redirect_to collection_url, :notice => "Task: #{resource.body} is undone!"
  end
  
  #Favorite Feature
  
  def favorite
    unless current_user.favorited_tasks.include?(resource)
      current_user.favorited_tasks << resource
      current_user.save
      redirect_to collection_url, :notice => "Task: #{resource.body} is favorited!"
    end
  end
  
  def unfavorite
    if current_user.favorited_tasks.include?(resource)
      current_user.favorited_tasks.delete resource
      current_user.save
      redirect_to collection_url, :notice => "Task: #{resource.body} is unfavorited!"
    end
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_tasks_helper.rb
module FavoriteTasksHelper
  include ApplicationHelper
end

app/helpers/project_assignments_helper.rb
module ProjectAssignmentsHelper
  include ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  include ApplicationHelper
end

app/helpers/task_assignments_helper.rb
module TaskAssignmentsHelper
  include ApplicationHelper
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
  include ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  include ApplicationHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
  include ApplicationHelper
end

app/views/favorite_tasks/_form.html.haml
= semantic_form_for @favorite_task do |form|
  = form.inputs do
    = form.input :user, :label => 'User'
    = form.input :task, :label => 'Task'
  = form.buttons

app/views/favorite_tasks/edit.html.haml
%h1 Editing favorite_task

= render 'form'

= link_to 'Show', @favorite_task
\|
= link_to 'Back', favorite_tasks_path

app/views/favorite_tasks/index.html.haml
%h1 Listing favorite_tasks

%table
  %tr
    %th User
    %th Task
    %th
    %th
    %th

  - @favorite_tasks.each do |favorite_task|
    %tr
      %td= favorite_task.user
      %td= favorite_task.task
      %td= link_to 'Show', favorite_task
      %td= link_to 'Edit', edit_favorite_task_path(favorite_task)
      %td= link_to 'Destroy', favorite_task, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Favorite task', new_favorite_task_path

app/views/favorite_tasks/new.html.haml
%h1 New favorite_task

= render 'form'

= link_to 'Back', favorite_tasks_path

app/views/favorite_tasks/show.html.haml
%p#notice= notice

%p
  %b User:
  = @favorite_task.user
%p
  %b Task:
  = @favorite_task.task

= link_to 'Edit', edit_favorite_task_path(@favorite_task)
\|
= link_to 'Back', favorite_tasks_path

app/views/projects/__index.html.haml
#project_container
  #project_nav
    - @projects.each do |project|
      =#link_to ("Add a fox", project, :remote=>true)
      .project_box{:href=>"/projects/#{project.id}"}
        %h2.name= project.name
        %h4.tasks_count= 12
        %h4.days_count= 15
  #project_detail
    - @projects[1].tasklists.each do |tasklist|
      .tasklist
        %h3.tasklist_name= tasklist.name
        - tasklist.tasks.each do |task|
          %p= task.body
  %span.clear &nbsp;

app/views/projects/_form.html.haml
= semantic_form_for @project do |form|
  = form.inputs do
    = form.input :name, :label => 'Name'
    = form.input :description, :label => 'Description'
    = form.input :deadline, :label => 'Deadline'
    = form.input :done, :label => 'Done'
    = form.input :completed_on, :label => 'Completed On'
    = form.input :active, :label => 'Active'
  = form.buttons

app/views/projects/_index.html.haml
%h1 Listing projects

%table
  %tr
    %th Name
    %th Description
    %th Deadline
    %th Done
    %th Completed on
    %th Active
    %th
    %th
    %th
    %th

  - @projects.each do |project|
    %tr
      %td= project.name
      %td= project.description
      %td= project.deadline
      %td= project.done
      %td= project.completed_on
      %td= project.active
      %td= link_to "(Tasklists)", project_tasklists_url(project)
      %td= link_to 'Show', project
      %td= link_to 'Edit', edit_project_path(project)
      %td= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Project', new_project_path

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %tr
    %th Name
    %th Description
    %th Deadline
    %th Done
    %th Completed on
    %th Active
    %th
    %th
    %th
    %th
    %th

  - @projects.each do |project|
    %tr
      %td= project.name
      %td= project.description
      %td= project.deadline
      %td= project.done
      %td= project.completed_on
      %td= project.active
      %td= link_to "(Tasklists)", project_tasklists_url(project)
      %td= link_to "(Team)", project_url(project) + '/manage_team'
      %td= link_to 'Show', project
      %td= link_to 'Edit', edit_project_path(project)
      %td= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Project', new_project_path

app/views/projects/manage_team.html.haml
= form_tag(:method => "post") do 
  %p 
    %h2 Current Team
    - @team.each do |team_member|
      = check_box_tag "team[user_#{team_member.id}]".to_sym, "1", true
      = label_tag "team[user_#{team_member.id}]".to_sym, team_member.email
  %p
    %h2 Other Users
    - @remaining_users.each do |other_member|
      = check_box_tag "team[user_#{other_member.id}]".to_sym, "1", false
      = label_tag "team[user_#{other_member.id}]".to_sym, other_member.email
      
  = submit_tag("Modify")
  
= link_to "Back to Project (#{@project.name})", project_path(@project)

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%h1= @project.name
%div
  %br
  - @project.tasklists.each do |tasklist|
    .tasklist
      %h4.tasklist_name= tasklist.name
      - tasklist.tasks.each do |task|
        %p= task.body
%div 
  %h2 Team
  
        
= link_to "Back to Project Index", projects_path
= link_to "Manage Team" 

app/views/task_assignments/_form.html.haml
= semantic_form_for @task_assignment do |form|
  = form.inputs do
    = form.input :task, :label => 'Task'
    = form.input :user, :label => 'User'
  = form.buttons

app/views/task_assignments/edit.html.haml
%h1 Editing task_assignment

= render 'form'

= link_to 'Show', @task_assignment
\|
= link_to 'Back', task_assignments_path

app/views/task_assignments/index.html.haml
%h1 Listing task_assignments

%table
  %tr
    %th Task
    %th User
    %th
    %th
    %th

  - @task_assignments.each do |task_assignment|
    %tr
      %td= task_assignment.task
      %td= task_assignment.user
      %td= link_to 'Show', task_assignment
      %td= link_to 'Edit', edit_task_assignment_path(task_assignment)
      %td= link_to 'Destroy', task_assignment, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Task assignment', new_task_assignment_path

app/views/task_assignments/new.html.haml
%h1 New task_assignment

= render 'form'

= link_to 'Back', task_assignments_path

app/views/task_assignments/show.html.haml
%p#notice= notice

%p
  %b Task:
  = @task_assignment.task
%p
  %b User:
  = @task_assignment.user

= link_to 'Edit', edit_task_assignment_path(@task_assignment)
\|
= link_to 'Back', task_assignments_path

app/views/tasklists/_form.html.haml
= semantic_form_for @tasklist, :url => params[:action] == 'new' ? collection_url : resource_url(resource) do |form|
  = form.inputs do
    = form.input :project, :label => 'Project'
    = form.input :name, :label => 'Name'
    = form.input :details, :label => 'Details'
  = form.buttons

app/views/tasklists/edit.html.haml
%h1 Editing tasklist

= render 'form'

= link_to 'Show', resource_url(@tasklist)
\|
= link_to 'Back', collection_url

app/views/tasklists/index.html.haml
%h1= "Listing Tasklists for #{parent.name}"

%table
  %tr
    %th Name
    %th Details
    %th People in Tasklist
    %th
    %th
    %th
    %th

  - @tasklists.each do |tasklist|
    %tr
      %td= tasklist.name
      %td= tasklist.details
      %td
        - if tasklist.assigned_users.size > 0
          %ul
            - tasklist.assigned_users.each do |user|
              %li= user
        - else
          No users assigned
      %td= link_to "(Tasks)", tasklist_tasks_url(tasklist)
      %td= link_to 'Show', resource_url(tasklist)
      %td= link_to 'Edit', edit_resource_url(tasklist)
      %td= link_to 'Destroy', resource_url(tasklist), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Tasklist', new_resource_url
= link_to "Back to Project: #{parent.name}", parent_url
= link_to "Back to Projects", projects_url

app/views/tasklists/new.html.haml
%h1 New tasklist

= render 'form'

= link_to 'Back', collection_url

app/views/tasklists/show.html.haml
%p#notice= notice

%p
  %b Project:
  = @tasklist.project
%p
  %b Name:
  = @tasklist.name
%p
  %b Details:
  = @tasklist.details
%p
  %b People:
  - if @tasklist.assigned_users.size > 0
    %ul
      - @tasklist.assigned_users.each do |user|
        %li= user
  - else
    No users assigned

%hr/  

%p
  %b= link_to "Tasks", tasklist_tasks_url(@tasklist)
  %br/
  %ul
    - @tasklist.tasks.each do |task|
      %li= link_to "#{task.body}", tasklist_task_url(@tasklist, task)

= link_to 'Edit', edit_resource_url(@tasklist)
\|
= link_to 'Back', collection_url

app/views/tasks/_form.html.haml
= semantic_form_for @task, :url => params[:action] == 'new' ? collection_url : resource_url(resource) do |form|
  = form.inputs do
    = form.input :tasklist, :label => 'Tasklist'
    = form.input :body, :label => 'Body'
    = form.input :user, :label => 'User'
    = form.input :done, :label => 'Done'
    = form.input :deadline, :label => 'Deadline'
    = form.input :started, :label => 'Started'
    = form.input :completed_on, :label => 'Completed On'
    = form.input :assigned_users, :as => :check_boxes
  = form.buttons

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', resource_url
\|
= link_to 'Back', collection_url

app/views/tasks/index.html.haml
%h1= "Listing Tasks for #{parent.name}"

%table
  %tr
    %th Body
    %th User
    %th Done
    %th Deadline
    %th Started
    %th Completed on
    %th Assigned Users
    %th
    %th
    %th
    %th
    %th
    %th

  - @tasks.each do |task|
    %tr
      %td= task.body
      %td= task.user
      %td= task.done
      %td= task.deadline
      %td= task.started ? task.started.nice_datetime : "Not started."
      %td= task.completed_on ? task.completed_on.nice_datetime : "Not completed."
      %td
        - if task.assigned_users.size > 0
          %ul
            - task.assigned_users.each do |user|
              %li= user
        - else
          No users assigned

      - if task.started
        %td= link_to 'Unstart!', unstart_tasklist_task_url(task.tasklist, task), :method => :put   
      - else
        %td= link_to 'Start!', start_tasklist_task_url(task.tasklist, task), :method => :put 

      - if task.done
        %td= link_to 'Mark as Undone!', undone_tasklist_task_url(task.tasklist, task), :method => :put   
      - else
        %td= link_to 'Mark as Done!', done_tasklist_task_url(task.tasklist, task), :method => :put 
    
      - unless current_user.favorited_tasks.include?(task)
        %td= link_to 'Favorite this!', favorite_tasklist_task_url(task.tasklist, task), :method => :put   
      - else
        %td= link_to 'Unfavorite this!', unfavorite_tasklist_task_url(task.tasklist, task), :method => :put   
        
      %td= link_to 'Show', resource_url(task)
      %td= link_to 'Edit', edit_resource_url(task)
      %td= link_to 'Destroy', resource_url(task), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Task', new_resource_url
= link_to "Back to Tasklist: #{parent.name}", project_tasklist_url(parent.project, parent)

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', collection_url

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Tasklist:
  = @task.tasklist
%p
  %b Body:
  = @task.body
%p
  %b Creator:
  = @task.user
%p
  %b Done:
  = @task.done
%p
  %b Deadline:
  = @task.deadline
%p
  %b Started:
  = @task.started
%p
  %b Completed on:
  = @task.completed_on

- if @task.assigned_users.size > 0
  %p
    %b Assigned Users:
    %ul
      - @task.assigned_users.each do |user|
        %li= user

= link_to 'Edit', edit_resource_url(@task)
\|
= link_to 'Back', collection_url

app/views/timelines/_form.html.haml
= semantic_form_for @timeline do |form|
  = form.inputs do
    = form.input :user, :label => 'User'
    = form.input :message, :label => 'Message'
    = form.input :link, :label => 'Link'
  = form.buttons

app/views/timelines/edit.html.haml
%h1 Editing timeline

= render 'form'

= link_to 'Show', @timeline
\|
= link_to 'Back', timelines_path

app/views/timelines/index.html.haml
%h1 Listing timelines

%table
  %tr
    %th
    %th
    %th
    %th

  - @timelines.each do |timeline|
    %tr
      %td
        =raw "#{timeline.user} #{timeline.message} #{link_to timeline.link, timeline.link}"
        &nbsp;
      %td= link_to 'Show', timeline
      %td= link_to 'Edit', edit_timeline_path(timeline)
      %td= link_to 'Destroy', timeline, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Timeline', new_timeline_path

app/views/timelines/new.html.haml
%h1 New timeline

= render 'form'

= link_to 'Back', timelines_path

app/views/timelines/show.html.haml
%p#notice= notice

%p
  %b User:
  = @timeline.user
%p
  %b Message:
  = @timeline.message
%p
  %b Link:
  = @timeline.link

= link_to 'Edit', edit_timeline_path(@timeline)
\|
= link_to 'Back', timelines_path